# Generated by Django 5.0.3 on 2024-12-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eu', '0002_school_teacher_email_teacher_password_turmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='_class',
            field=models.CharField(default='3 - Informática', max_length=100),
        ),
    ]
