# Generated by Django 5.0.3 on 2024-12-06 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eu', '0003_student__class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_class',
            new_name='clasS',
        ),
    ]
